app:
  use_depth_image:  0

kitti:
  dataset_path:   "../data/KITTI"

  focal_u_cam2:   718.856
  focal_v_cam2:   718.856
  center_u_cam2:  607.1928
  center_v_cam2:  185.2157

  gnss_calib_x:   -0.05
  gnss_calib_y:   0.32
  gnss_calib_z:   0.63

  imu_calib_x:   -0.05
  imu_calib_y:   0.32
  imu_calib_z:   0.63

metric3d:
  model_path:   "./lib/Metric3D"
  model_name:   "metric3d_vit_small"
  ckpt_path:    "metric_depth_vit_small_800k"